services:
  mongodb:
    image: mongo:8.0.13
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - app_network
  postgres:
    image: postgres:16.10
    container_name: postgres
    ports:
      - "5678:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app_network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app_network
  ollama:
    image: ollama/ollama:0.6.8
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Remove the GPU section if you don't have NVIDIA GPU
  spark:
    image: docker-spark:3.5.5
    container_name: spark
    ports:
      - "4040:4040"  # Spark UI
    volumes:
      - ../data-pipelines:/app/data-pipelines
    networks:
      - app_network

volumes:
  pgdata:
  mongodb_data:
  elasticsearch-data:
  ollama_data:

networks:
  app_network:
    driver: bridge
